# Generated by Django 2.0.6 on 2019-03-11 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeSchoolRecipeApp', '0002_auto_20190311_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealModel',
            new_name='RecipeModel',
        ),
    ]
