# Generated by Django 2.0.6 on 2019-03-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSchoolRecipeApp', '0003_auto_20190311_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(default='', max_length=200)),
                ('ingredients', models.IntegerField(default=0)),
                ('directions', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='recipemodel',
            old_name='pictureURL',
            new_name='mealPicture',
        ),
        migrations.RenameField(
            model_name='recipemodel',
            old_name='shortDescription',
            new_name='nameOfMeal',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='profilePicture',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='recipeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeSchoolRecipeApp.RecipeModel'),
        ),
    ]
