# Generated by Django 2.0.6 on 2019-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSchoolRecipeApp', '0004_auto_20190311_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='creatorOfRecipe',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='password1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='password2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
