# Generated by Django 2.0.6 on 2019-03-11 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeSchoolRecipeApp', '0005_auto_20190311_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='dateCreated',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='mealPicture',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='nameOfMeal',
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='mealPicture',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='detailmodel',
            name='nameOfMeal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='foreignkeyToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
