# Generated by Django 2.0.6 on 2019-03-11 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CodeSchoolRecipeApp', '0007_remove_recipemodel_foreignkeytouser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailmodel',
            name='recipeModel',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='directions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='foreignkeyToUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='mealPicture',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='nameOfMeal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='shortDescription',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='DetailModel',
        ),
    ]
