# Generated by Django 2.0.6 on 2019-03-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSchoolRecipeApp', '0008_auto_20190311_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('profilePicture', models.CharField(default='', max_length=800)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='profilePicture',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='username',
        ),
    ]
