# Generated by Django 2.0.6 on 2019-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeSchoolRecipeApp', '0009_auto_20190311_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='ingredients',
            field=models.CharField(default='', max_length=800),
        ),
    ]
